modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/tgstyle/MCT-Immersive-Technology/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivetechnology"
	version="${version}"
	displayName="Immersive Technology"
	description="More Machines for Immersive Engineering"
	authors="tgstyle, Kurtchekov"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology"
	issueTrackerURL="https://github.com/tgstyle/MCT-Immersive-Technology"
	logoFile="logo.png"
	credits="BluSunrize for Immersive Engineering, derived from Immersive Tech by FerroO2000"

	[[dependencies.immersivetechnology]]
		modId="forge"
		mandatory=true
		versionRange="[28,)"
		ordering="NONE"
		side="BOTH"

	[[dependencies.immersivetechnology]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.16,1.17)"
		ordering="NONE"
		side="BOTH"

	[[dependencies.immersivetechnology]]
		modId="immersiveengineering"
		mandatory=true
		versionRange="[1.16.4-4,1.17-4)"
		ordering="AFTER"
		side="BOTH"